In [21]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
df = pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Loan%20Status.csv")

In [23]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [25]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [26]:
df.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [27]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [28]:
df.shape

(614, 13)

In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [31]:
df['ApplicantIncome'].unique()

array([ 5849,  4583,  3000,  2583,  6000,  5417,  2333,  3036,  4006,
       12841,  3200,  2500,  3073,  1853,  1299,  4950,  3596,  3510,
        4887,  2600,  7660,  5955,  3365,  3717,  9560,  2799,  4226,
        1442,  3750,  4166,  3167,  4692,  3500, 12500,  2275,  1828,
        3667,  3748,  3600,  1800,  2400,  3941,  4695,  3410,  5649,
        5821,  2645,  4000,  1928,  3086,  4230,  4616, 11500,  2708,
        2132,  3366,  8080,  3357,  3029,  2609,  4945,  5726, 10750,
        7100,  4300,  3208,  1875,  4755,  5266,  1000,  3333,  3846,
        2395,  1378,  3988,  2366,  8566,  5695,  2958,  6250,  3273,
        4133,  3620,  6782,  2484,  1977,  4188,  1759,  4288,  4843,
       13650,  4652,  3816,  3052, 11417,  7333,  3800,  2071,  5316,
        2929,  3572,  7451,  5050, 14583,  2214,  5568, 10408,  5667,
        2137,  2957,  3692, 23803,  3865, 10513,  6080, 20166,  2014,
        2718,  3459,  4895,  3316, 14999,  4200,  5042,  6950,  2698,
       11757,  2330, 14866,  1538, 10000,  4860,  6277,  2577,  9166,
        2281,  3254, 39999,  9538,  2980,  1863,  7933,  3089,  4167,
        9323,  3707,  2439,  2237,  8000,  1820, 51763,  3522,  5708,
        4344,  3497,  2045,  5516,  6400,  1916,  4600, 33846,  3625,
       39147,  2178,  2383,   674,  9328,  4885, 12000,  6033,  3858,
        4191,  3125,  8333,  1907,  3416, 11000,  4923,  3992,  3917,
        4408,  3244,  3975,  2479,  3418,  3430,  7787,  5703,  3173,
        3850,   150,  3727,  5000,  4283,  2221,  4009,  2971,  7578,
        3250,  4735,  4758,  2491,  3716,  3189,  3155,  5500,  5746,
        3463,  3812,  3315,  5819,  2510,  2965,  3406,  6050,  9703,
        6608,  2882,  1809,  1668,  3427,  2661, 16250,  3083,  6045,
        5250, 14683,  4931,  6083,  2060,  3481,  7200,  5166,  4095,
        4708,  4333,  2876,  3237, 11146,  2833,  2620,  3900,  2750,
        3993,  3103,  4100,  4053,  3927,  2301,  1811, 20667,  3158,
        3704,  4124,  9508,  3075,  4400,  3153,  4416,  6875,  4666,
        2875,  1625,  2000,  3762, 20233,  7667,  2917,  2927,  2507,
        2473,  3399,  2058,  3541,  4342,  3601,  3166, 15000,  8666,
        4917,  5818,  4384,  2935, 63337,  9833,  5503,  1830,  4160,
        2647,  2378,  4554,  2499,  3523,  6333,  2625,  9083,  8750,
        2666,  2423,  3813,  3875,  5167,  4723,  4750,  3013,  6822,
        6216,  5124,  6325, 19730, 15759,  5185,  3062,  2764,  4817,
        4310,  3069,  5391,  5941,  7167,  4566,  2346,  3010,  5488,
        9167,  9504,  1993,  3100,  3276,  3180,  3033,  3902,  1500,
        2889,  2755,  1963,  7441,  4547,  2167,  2213,  8300, 81000,
        3867,  6256,  6096,  2253,  2149,  2995,  1600,  1025,  3246,
        5829,  2720,  7250, 14880,  4606,  5935,  2920,  2717,  8624,
        6500, 12876,  2425, 10047,  1926, 10416,  7142,  3660,  7901,
        4707, 37719,  3466,  3539,  3340,  2769,  2309,  1958,  3948,
        2483,  7085,  3859,  4301,  3708,  4354,  8334,  2083,  7740,
        3015,  5191,  2947, 16692,   210,  3450,  2653,  4691,  5532,
       16525,  6700,  2873, 16667,  4350,  3095, 10833,  3547, 18333,
        2435,  2699,  5333,  3691, 17263,  3597,  3326,  4625,  2895,
        6283,   645,  3159,  4865,  4050,  3814, 20833,  3583, 13262,
        3598,  6065,  3283,  2130,  5815,  2031,  3074,  4683,  3400,
        2192,  5677,  7948,  4680, 17500,  3775,  5285,  2679,  6783,
        4281,  3588, 11250, 18165,  2550,  6133,  3617,  6417,  4608,
        2138,  3652,  2239,  3017,  2768,  3358,  2526,  2785,  6633,
        2492,  2454,  3593,  5468,  2667, 10139,  3887,  4180,  3675,
       19484,  5923,  5800,  8799,  4467,  3417,  5116, 16666,  6125,
        6406,  3087,  3229,  1782,  3182,  6540,  1836,  1880,  2787,
        2297,  2165,  2726,  9357, 16120,  3833,  6383,  2987,  9963,
        5780,   416,  2894,  3676,  3987,  3232,  2900,  4106,  8072,
        7583])

In [32]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data=lb.fit_transform(df['Loan_Status'])
data

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [33]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
df_1=np.array([df['Loan_Status']]).reshape(-1,1)
data=onehot_encoder.fit_transform(df_1)
data

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [34]:
df['Gender']=df["Gender"].map({"Male":1,"Female":0})
df['Married']=df['Married'].map({"yes":1,"No":1})
df['Education']=df['Education'].map({"Graduate":1,"Not Graduate":0})
df['Dependents'].replace('3+',3,inplace=True)
df['Self_Employed']=df['Self_Employed'].map({"yes":1,"No":0})
df['Property_Area']=df['Property_Area'].map({"Semiurban":1,"Urban":0})
df['Loan_Status']=df['Loan_Status'].map({"Yes":1,"No":0})

In [35]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1.0,1.0,0,1,0.0,5849,0.0,NaN,360.0,1.0,0.0,NaN
1,LP001003,1.0,NaN,1,1,0.0,4583,1508.0,128.0,360.0,1.0,NaN,NaN
2,LP001005,1.0,NaN,0,1,NaN,3000,0.0,66.0,360.0,1.0,0.0,NaN
3,LP001006,1.0,NaN,0,0,0.0,2583,2358.0,120.0,360.0,1.0,0.0,NaN
4,LP001008,1.0,1.0,0,1,0.0,6000,0.0,141.0,360.0,1.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,0.0,1.0,0,1,0.0,2900,0.0,71.0,360.0,1.0,NaN,NaN
610,LP002979,1.0,NaN,3,1,0.0,4106,0.0,40.0,180.0,1.0,NaN,NaN
611,LP002983,1.0,NaN,1,1,0.0,8072,240.0,253.0,360.0,1.0,0.0,NaN
612,LP002984,1.0,NaN,2,1,0.0,7583,0.0,187.0,360.0,1.0,0.0,NaN
613,LP002990,0.0,1.0,0,1,NaN,4583,0.0,133.0,360.0,0.0,1.0,NaN

In [36]:
rev_null=['Gender','Married','Dependents','Self_Employed','Credit_History','LoanAmount','Loan_Amount_Term']
df[rev_null]=df[rev_null].replace({np.nan:df['Gender'].mode(),np.nan:df['Married'].mode(),np.nan:df['Dependents'].mode(),np.nan:df['Self_Employed'].mode(),np.nan:df['Credit_History'].mode(),np.nan:df['LoanAmount'].mode(),np.nan:df['Loan_Amount_Term'].mode()})

In [37]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1.0,1.0,0,1,0.0,5849,0.0,NaN,360.0,1.0,0.0,NaN
1,LP001003,1.0,NaN,1,1,0.0,4583,1508.0,128.0,360.0,1.0,NaN,NaN
2,LP001005,1.0,NaN,0,1,NaN,3000,0.0,66.0,360.0,1.0,0.0,NaN
3,LP001006,1.0,NaN,0,0,0.0,2583,2358.0,120.0,360.0,1.0,0.0,NaN
4,LP001008,1.0,1.0,0,1,0.0,6000,0.0,141.0,360.0,1.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,0.0,1.0,0,1,0.0,2900,0.0,71.0,360.0,1.0,NaN,NaN
610,LP002979,1.0,NaN,3,1,0.0,4106,0.0,40.0,180.0,1.0,NaN,NaN
611,LP002983,1.0,NaN,1,1,0.0,8072,240.0,253.0,360.0,1.0,0.0,NaN
612,LP002984,1.0,NaN,2,1,0.0,7583,0.0,187.0,360.0,1.0,0.0,NaN
613,LP002990,0.0,1.0,0,1,NaN,4583,0.0,133.0,360.0,0.0,1.0,NaN